package com.alipay.orderservice.domain;

import java.math.BigDecimal;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PayRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_record.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_record.ORDER_NO
     *
     * @mbg.generated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_record.ACCOUNT_CODE
     *
     * @mbg.generated
     */
    private String accountCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_record.PRODUCT_CODE
     *
     * @mbg.generated
     */
    private String productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_record.COUNT
     *
     * @mbg.generated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_record.AMOUNT
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_record.ID
     *
     * @return the value of pay_record.ID
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_record.ID
     *
     * @param id the value for pay_record.ID
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_record.ORDER_NO
     *
     * @return the value of pay_record.ORDER_NO
     * @mbg.generated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_record.ORDER_NO
     *
     * @param orderNo the value for pay_record.ORDER_NO
     * @mbg.generated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_record.ACCOUNT_CODE
     *
     * @return the value of pay_record.ACCOUNT_CODE
     * @mbg.generated
     */
    public String getAccountCode() {
        return accountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_record.ACCOUNT_CODE
     *
     * @param accountCode the value for pay_record.ACCOUNT_CODE
     * @mbg.generated
     */
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode == null ? null : accountCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_record.PRODUCT_CODE
     *
     * @return the value of pay_record.PRODUCT_CODE
     * @mbg.generated
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_record.PRODUCT_CODE
     *
     * @param productCode the value for pay_record.PRODUCT_CODE
     * @mbg.generated
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_record.COUNT
     *
     * @return the value of pay_record.COUNT
     * @mbg.generated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_record.COUNT
     *
     * @param count the value for pay_record.COUNT
     * @mbg.generated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_record.AMOUNT
     *
     * @return the value of pay_record.AMOUNT
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_record.AMOUNT
     *
     * @param amount the value for pay_record.AMOUNT
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_record
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderNo=").append(orderNo);
        sb.append(", accountCode=").append(accountCode);
        sb.append(", productCode=").append(productCode);
        sb.append(", count=").append(count);
        sb.append(", amount=").append(amount);
        sb.append("]");
        return sb.toString();
    }
}