server:
  port: 9999
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: account-api
          uri: 'http://localhost:8010'
          predicates:
            - Path=/account/**
        - id: order-api
          uri: 'http://localhost:8013'
          predicates:
            - Path=/order/**