package com.alipay.orderservice.mapper;

import com.alipay.orderservice.domain.PayRecord;
import com.alipay.orderservice.domain.PayRecordExample;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PayRecordMapper extends BaseMapper<PayRecord> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_record
     *
     * @mbg.generated
     */
    long countByExample(PayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_record
     *
     * @mbg.generated
     */
    int deleteByExample(PayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_record
     *
     * @mbg.generated
     */
    int insert(PayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_record
     *
     * @mbg.generated
     */
    int insertSelective(PayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_record
     *
     * @mbg.generated
     */
    List<PayRecord> selectByExample(PayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_record
     *
     * @mbg.generated
     */
    PayRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PayRecord record, @Param("example") PayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PayRecord record, @Param("example") PayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PayRecord record);
}