package com.alipay.orderservice.mapper;

import com.alipay.orderservice.domain.TransactionLog;
import com.alipay.orderservice.domain.TransactionLogExample;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TransactionLogMapper extends BaseMapper<TransactionLog> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_log
     *
     * @mbg.generated
     */
    long countByExample(TransactionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_log
     *
     * @mbg.generated
     */
    int deleteByExample(TransactionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_log
     *
     * @mbg.generated
     */
    int insert(TransactionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_log
     *
     * @mbg.generated
     */
    int insertSelective(TransactionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_log
     *
     * @mbg.generated
     */
    List<TransactionLog> selectByExample(TransactionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_log
     *
     * @mbg.generated
     */
    TransactionLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TransactionLog record, @Param("example") TransactionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TransactionLog record, @Param("example") TransactionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TransactionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TransactionLog record);
}